In [4]:
import torch 

x=torch.randn(3,requires_grad=True)
print(x)

y= x+2
print(y)
z = y*y*2
z= z.mean()
print(z)

v= torch.tensor([ 0.1,1.0,0.001], dtype = torch.float32)
z.backward() #dz/dx
print(x.grad)

tensor([ 0.6078, -1.4739,  0.3290], requires_grad=True)
tensor([2.6078, 0.5261, 2.3290], grad_fn=<AddBackward0>)
tensor(8.3345, grad_fn=<MeanBackward0>)
tensor([3.4771, 0.7014, 3.1054])


In [8]:
x=torch.randn(3,requires_grad=True)
print(x)

# x.requires_grad_(False)
# x.detach()
# with torch.no_grad() :

y= x+2
print(y)

tensor([-0.8385, -2.7534,  0.1183], requires_grad=True)
tensor([ 1.1615, -0.7534,  2.1183], grad_fn=<AddBackward0>)


In [13]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(4):
    model_output = (weights*3).sum()

    model_output.backward()
    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

In [ ]:
weights = torch.ones(4, requires_grad=True)

z.backward()
weights.grad.zero_() 
