https://www.youtube.com/watch?v=c36lUUr864M&t=1763s

Deep Learning With PyTorch - Full Course by Patrick Loeber

In [1]:
import torch

x = torch.empty(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
y = torch.rand(2,2)
y

tensor([[0.9321, 0.9896],
        [0.1773, 0.9846]])

In [14]:
z = torch.ones(2,2,dtype=torch.float16)
z.size()

torch.Size([2, 2])

In [17]:
x = torch.tensor([2.5,3])
x

tensor([2.5000, 3.0000])

In [22]:
x= torch.rand(2,2)
y= torch.rand(2,2)

print(x,'\n',y)

y.add_(x)
z= x+y
z= torch.add(x,y)

z= x-y
z= torch.sub(x,y)

z= x*y
z= torch.mul(x,y)

z= x/y
z= torch.div(x,y)



tensor([[0.5221, 0.8868],
        [0.4876, 0.3884]]) 
 tensor([[0.1422, 0.2418],
        [0.4941, 0.6007]])


In [29]:
x= torch.rand(5,3)
print(x)
print(x[1,1].item())

tensor([[0.3494, 0.8398, 0.9845],
        [0.3274, 0.1739, 0.4620],
        [0.9153, 0.2423, 0.6202],
        [0.6032, 0.3621, 0.6118],
        [0.1174, 0.9107, 0.0908]])
0.1739245057106018


In [33]:
x= torch.rand(4,4)
print(x)
y =x.view(16)
print(y)
## resize
y =x.view(-1,8)
print(y.size())

tensor([[0.2862, 0.2545, 0.4455, 0.4486],
        [0.2316, 0.4715, 0.1634, 0.2504],
        [0.8716, 0.7484, 0.9304, 0.8821],
        [0.6626, 0.0857, 0.2303, 0.7634]])
tensor([0.2862, 0.2545, 0.4455, 0.4486, 0.2316, 0.4715, 0.1634, 0.2504, 0.8716,
        0.7484, 0.9304, 0.8821, 0.6626, 0.0857, 0.2303, 0.7634])
torch.Size([2, 8])


In [36]:
import numpy as np 

a = torch.ones(5)
print(a)
b= a.numpy()
print(type(b))
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [38]:
a = np.ones(5)
print(a)
b= torch.from_numpy(a)
print(b)


a+=1 
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [10]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device= device)
    y=torch.ones(5)
    y=y.to(device)
    z=x+y
    z= z.to("cpu")
    
z

tensor([2., 2., 2., 2., 2.])

In [7]:
x= torch.ones(5, requires_grad= True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [2]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.is_available()

False

In [4]:
torch.tensor([[1,2]]).cuda()

tensor([[1, 2]], device='cuda:0')